/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as ProducersRouteImport } from './routes/producers'
import { Route as ModerationLogRouteImport } from './routes/moderation-log'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CommentsRouteImport } from './routes/comments'
import { Route as CheckinsRouteImport } from './routes/checkins'
import { Route as BeveragesRouteImport } from './routes/beverages'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducersRoute = ProducersRouteImport.update({
  id: '/producers',
  path: '/producers',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationLogRoute = ModerationLogRouteImport.update({
  id: '/moderation-log',
  path: '/moderation-log',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsRoute = CommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinsRoute = CheckinsRouteImport.update({
  id: '/checkins',
  path: '/checkins',
  getParentRoute: () => rootRouteImport,
} as any)
const BeveragesRoute = BeveragesRouteImport.update({
  id: '/beverages',
  path: '/beverages',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beverages': typeof BeveragesRoute
  '/checkins': typeof CheckinsRoute
  '/comments': typeof CommentsRoute
  '/login': typeof LoginRoute
  '/moderation-log': typeof ModerationLogRoute
  '/producers': typeof ProducersRoute
  '/queue': typeof QueueRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beverages': typeof BeveragesRoute
  '/checkins': typeof CheckinsRoute
  '/comments': typeof CommentsRoute
  '/login': typeof LoginRoute
  '/moderation-log': typeof ModerationLogRoute
  '/producers': typeof ProducersRoute
  '/queue': typeof QueueRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beverages': typeof BeveragesRoute
  '/checkins': typeof CheckinsRoute
  '/comments': typeof CommentsRoute
  '/login': typeof LoginRoute
  '/moderation-log': typeof ModerationLogRoute
  '/producers': typeof ProducersRoute
  '/queue': typeof QueueRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beverages'
    | '/checkins'
    | '/comments'
    | '/login'
    | '/moderation-log'
    | '/producers'
    | '/queue'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beverages'
    | '/checkins'
    | '/comments'
    | '/login'
    | '/moderation-log'
    | '/producers'
    | '/queue'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/beverages'
    | '/checkins'
    | '/comments'
    | '/login'
    | '/moderation-log'
    | '/producers'
    | '/queue'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeveragesRoute: typeof BeveragesRoute
  CheckinsRoute: typeof CheckinsRoute
  CommentsRoute: typeof CommentsRoute
  LoginRoute: typeof LoginRoute
  ModerationLogRoute: typeof ModerationLogRoute
  ProducersRoute: typeof ProducersRoute
  QueueRoute: typeof QueueRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producers': {
      id: '/producers'
      path: '/producers'
      fullPath: '/producers'
      preLoaderRoute: typeof ProducersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation-log': {
      id: '/moderation-log'
      path: '/moderation-log'
      fullPath: '/moderation-log'
      preLoaderRoute: typeof ModerationLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments': {
      id: '/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof CommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkins': {
      id: '/checkins'
      path: '/checkins'
      fullPath: '/checkins'
      preLoaderRoute: typeof CheckinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beverages': {
      id: '/beverages'
      path: '/beverages'
      fullPath: '/beverages'
      preLoaderRoute: typeof BeveragesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeveragesRoute: BeveragesRoute,
  CheckinsRoute: CheckinsRoute,
  CommentsRoute: CommentsRoute,
  LoginRoute: LoginRoute,
  ModerationLogRoute: ModerationLogRoute,
  ProducersRoute: ProducersRoute,
  QueueRoute: QueueRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
