// AUTOGENERATED by scripts/gen-tokens.sh from design/tokens.json — do not edit.
// To change a token: edit design/tokens.json and re-run scripts/gen-tokens.sh.

export const tokens = {
  "colors": {
    "mizu": "#B6D6E2",
    "sora": "#88B7D6",
    "hanada": "#4A86A8",
    "ai": "#165E83",
    "kon": "#0F2350",
    "rurikon": "#1B264F",
    "sumi": "#14171F",
    "shironeri": "#FCFAF6",
    "kinari": "#F4EFE6",
    "gray50": "#F5F7FA",
    "gray100": "#ECEFF4",
    "gray200": "#DCE2EA",
    "gray300": "#C2CBD6",
    "gray400": "#95A2B3",
    "gray500": "#6B7787",
    "gray600": "#4A5462",
    "gray700": "#2F3640",
    "gray800": "#1B1F26",
    "koh": "#C97B5A",
    "matcha": "#6B8E5C",
    "akane": "#A23B3B",
    "yamabuki": "#D4A845"
  },
  "semantic": {
    "fg1": "#14171F",
    "fg2": "#4A5462",
    "fg3": "#6B7787",
    "fgMuted": "#95A2B3",
    "fgOnDark": "#FCFAF6",
    "fgLink": "#165E83",
    "fgBrand": "#165E83",
    "fgSuccess": "#6B8E5C",
    "fgWarning": "#D4A845",
    "fgDanger": "#A23B3B",
    "bgPage": "#FCFAF6",
    "bgSurface": "#FFFFFF",
    "bgSunken": "#F5F7FA",
    "bgCard": "#FFFFFF",
    "bgWarm": "#F4EFE6",
    "bgBrand": "#165E83",
    "bgBrandDeep": "#0F2350",
    "bgTintMizu": "#EAF3F8",
    "bgSuccess": "#E8EFE3",
    "bgWarning": "#F6EBCB",
    "bgDanger": "#F4DFDF",
    "border1": "#DCE2EA",
    "border2": "#C2CBD6",
    "borderStrong": "#2F3640",
    "borderBrand": "#165E83"
  },
  "spacing": {
    "s1": 4,
    "s2": 8,
    "s3": 12,
    "s4": 16,
    "s5": 20,
    "s6": 24,
    "s7": 32,
    "s8": 40,
    "s9": 48,
    "s10": 64,
    "s11": 80,
    "s12": 96,
    "named": {
      "xs": 4,
      "sm": 8,
      "md": 12,
      "lg": 16,
      "xl": 24,
      "xxl": 32
    }
  },
  "radii": {
    "xs": 4,
    "sm": 8,
    "md": 12,
    "lg": 16,
    "xl": 24,
    "pill": 999
  },
  "typography": {
    "displayFamily": "Shippori Mincho",
    "bodyFamily": "Noto Sans JP",
    "monoFamily": "JetBrains Mono",
    "sizes": {
      "display": 44,
      "h1": 32,
      "h2": 24,
      "h3": 20,
      "body": 16,
      "small": 14,
      "caption": 12,
      "overline": 11
    }
  },
  "motion": {
    "durFastMs": 120,
    "durBaseMs": 200,
    "durSlowMs": 320
  }
} as const;

export type Tokens = typeof tokens;
