// Stage 7 (ARCH-011) — KAMOS design-token codegen helper.
//
// Invoked by scripts/gen-tokens.sh:
//   node scripts/gen-tokens.js <tokens.json> <admin/src/lib/tokens.ts>
//
// Reads the canonical JSON, strips comment keys (any key starting with
// '_'), and writes the admin TypeScript export. Idempotent.

'use strict';

const fs = require('fs');
const path = require('path');

if (process.argv.length < 4) {
  console.error('usage: node gen-tokens.js <tokens.json> <out.ts>');
  process.exit(1);
}

const tokensPath = process.argv[2];
const outPath = process.argv[3];

const tokens = JSON.parse(fs.readFileSync(tokensPath, 'utf8'));

// Recursively strip comment keys (leading underscore).
function strip(value) {
  if (Array.isArray(value)) return value.map(strip);
  if (value && typeof value === 'object') {
    const out = {};
    for (const [k, v] of Object.entries(value)) {
      if (k.startsWith('_')) continue;
      out[k] = strip(v);
    }
    return out;
  }
  return value;
}

const cleaned = strip(tokens);
const banner =
  '// AUTOGENERATED by scripts/gen-tokens.sh from design/tokens.json — do not edit.\n' +
  '// To change a token: edit design/tokens.json and re-run scripts/gen-tokens.sh.\n';

const body =
  banner +
  '\n' +
  'export const tokens = ' +
  JSON.stringify(cleaned, null, 2) +
  ' as const;\n' +
  '\n' +
  'export type Tokens = typeof tokens;\n';

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, body);
